site_name: WaterALLOC User Manual
theme: 
markdown_extensions:
    - toc:
        baselevel: 1
    - pymdownx.tabbed
nav:
    - Home: index.md
    - Modules:
        - Settings and Options: General.md
        - HydroBID:
            - Creating a Folder: Modules/HydroBID/HydroBID_Main.md
        - HydroRAM:
            - Measured Flows: Modules/HydroRAM/MeasuredFlows.md
        - MODSIM:
            - Main: Modules/MODSIM/MODSIMModule.md
            - Reservoir Shape Import: Modules/MODSIM/ResShapefImport.md
            - Simplifying Network: Modules/MODSIM/SimplyfyingNetwork.md
            - Time Series Import: Modules/MODSIM/TimeseriesImport.md
    - WaterALLOC:
        - Scenarios: WaterALLOC/Scenarios.md
    - About: about.md

